# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - PowerBiInclusive
variables:
  uiSource : 'src'
  uiBuild : '$(uiSource)/build'


jobs:
  - job: First_job
    displayName: Agent job 1
    timeoutInMinutes: 0
    pool:
      vmImage: windows-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        pushd $(uiSource)
        npm install
        npm run ci --legacy-peer-deps
        popd
      displayName: 'npm install and build'

    
    - task: ArchiveFiles@2
      displayName: Archive Build
      inputs:
        rootFolderOrFile: build
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(TargetFolder)'
      inputs:
        SourceFolder: build
        Contents: $(Build.BuildId).zip
        TargetFolder: $(Build.ArtifactStagingDirectory)\StagingArtifactsToBePublished
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: build
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'