export const baseUrl = "https://localhost:7103/api"
//export const baseUrl = "https://unifiedlicenseapi.azurewebsites.net"
//export const baseUrl = "https://unifiedlicense20230601104842.azurewebsites.net/api"
//export const baseUrl = "https://unifiedlicenseportal20230724115858.azurewebsites.net/api"
//export const baseUrl = "https://appmanageapi.azurewebsites.net/api"